// =============================================================================
// MediCaPlus — Invoice Preview & Download
//
// Shows the SERVER's invoice PDF (GET /vsArogya/prev-invoice/:id → 302 redirect
// to the hosted PDF, followed by the client; or the order's invoiceUrl). This
// is the invoice generated by the backend — nothing is rendered on-device. If
// the server can't provide one, the exact reason is shown with a Try again.
// =============================================================================

import 'dart:typed_data';

import 'package:flutter/material.dart';
import 'package:printing/printing.dart';

import '../vendor_registration_screen.dart' show AppColors;
import 'customer_api.dart';
import 'customer_models.dart';
import 'invoice_pdf.dart' show InvoicePdf;

class InvoicePreviewScreen extends StatefulWidget {
  const InvoicePreviewScreen({super.key, required this.order});

  final Order order;

  @override
  State<InvoicePreviewScreen> createState() => _InvoicePreviewScreenState();
}

class _InvoicePreviewScreenState extends State<InvoicePreviewScreen> {
  final CustomerApi _api = CustomerApi();
  late Future<(Uint8List?, String?)> _future;

  @override
  void initState() {
    super.initState();
    _future = _load();
  }

  /// Fetches the server invoice, POLLING briefly when it isn't ready yet —
  /// right after checkout the backend is still generating/linking the PDF, so
  /// "Invoice not found" for the first few seconds is normal, not an error.
  Future<(Uint8List?, String?)> _load() async {
    var result = await _api.fetchServerInvoice(widget.order);
    var attempt = 0;
    // Render free tier pe PDF (22-page + cold Chrome) 30-60s le sakta hai —
    // isliye ~90s tak har 5s me retry karo before giving up.
    while (mounted &&
        result.$1 == null &&
        (result.$2 ?? '').toLowerCase().contains('invoice not found') &&
        attempt < 18) {
      await Future.delayed(const Duration(seconds: 5));
      if (!mounted) break;
      result = await _api.fetchServerInvoice(widget.order);
      attempt++;
    }
    if (result.$1 == null &&
        (result.$2 ?? '').toLowerCase().contains('invoice not found')) {
      return (
        null,
        'Your invoice is still being generated. Please try again in a few '
        'seconds.'
      );
    }
    return result;
  }

  @override
  void dispose() {
    _api.dispose();
    super.dispose();
  }

  void _retry() {
    // Block body — an arrow here returns the assignment's value (a Future),
    // which setState rejects ("callback argument returned a Future").
    setState(() {
      _future = _load();
    });
  }

  String get _fileName => '${InvoicePdf.invoiceNo(widget.order.id)}.pdf';

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.pageBg,
      appBar: AppBar(
        backgroundColor: Colors.white,
        foregroundColor: AppColors.darkText,
        elevation: 0.5,
        title: const Text('Invoice',
            style: TextStyle(fontWeight: FontWeight.w800)),
      ),
      body: FutureBuilder<(Uint8List?, String?)>(
        future: _future,
        builder: (context, snapshot) {
          if (snapshot.connectionState != ConnectionState.done) {
            return _loading();
          }
          final bytes = snapshot.data?.$1;
          final error = snapshot.data?.$2;
          if (bytes != null && bytes.isNotEmpty) {
            return PdfPreview(
              build: (_) => bytes,
              useActions: true,
              allowPrinting: true,
              allowSharing: true,
              canChangePageFormat: false,
              canChangeOrientation: false,
              canDebug: false,
              pdfFileName: _fileName,
              loadingWidget: _loading(),
              previewPageMargin: const EdgeInsets.all(12),
            );
          }
          return _errorView(error ?? 'Could not load the invoice.');
        },
      ),
    );
  }

  Widget _loading() {
    return const Center(
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          CircularProgressIndicator(color: AppColors.primary),
          SizedBox(height: 16),
          Text('Loading invoice…',
              style: TextStyle(color: AppColors.greyText, fontSize: 13.5)),
        ],
      ),
    );
  }

  Widget _errorView(String message) {
    return Center(
      child: Padding(
        padding: const EdgeInsets.all(24),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            const Icon(Icons.receipt_long_outlined,
                size: 48, color: AppColors.greyText),
            const SizedBox(height: 14),
            const Text('Invoice unavailable',
                style: TextStyle(fontSize: 15, fontWeight: FontWeight.w700)),
            const SizedBox(height: 6),
            Text(
              message,
              textAlign: TextAlign.center,
              style: const TextStyle(color: AppColors.greyText, fontSize: 13),
            ),
            const SizedBox(height: 18),
            OutlinedButton.icon(
              onPressed: _retry,
              icon: const Icon(Icons.refresh, size: 18),
              label: const Text('Try again'),
              style: OutlinedButton.styleFrom(
                foregroundColor: AppColors.darkGreen,
                side: const BorderSide(color: AppColors.primary),
                padding:
                    const EdgeInsets.symmetric(horizontal: 20, vertical: 12),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
